version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    hostname: postgres
    container_name: postgres-docker-assignment
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    restart: always
    hostname: redis
    container_name: redis-docker-basics-assignment
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp
    hostname: goapp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}

volumes:
  pgdata:
  redis-data: