services:
  postgres:
    image: postgres:16
    restart: always
    hostname: postgres
    container_name: postgres-docker-assignment
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7.4
    restart: always
    hostname: redis
    container_name: redis-docker-basics-assignment
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
    networks:
      - internal

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp
    hostname: goapp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - migration
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    networks:
      - internal
      - external

  migration:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "${DATABASE_URL}", "up" ]
    depends_on:
      - postgres
    networks:
      - internal
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable

volumes:
  pgdata:
  redis-data:

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
    internal: false